// Especifica la versión de la sintaxis de Protocol Buffers.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: michael.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Mission_Oferta_FullMethodName             = "/mensaje.Mission/Oferta"
	Mission_ConfirmMission_FullMethodName     = "/mensaje.Mission/ConfirmMission"
	Mission_Distraccion_FullMethodName        = "/mensaje.Mission/Distraccion"
	Mission_Golpe_FullMethodName              = "/mensaje.Mission/Golpe"
	Mission_NotificarEstrellas_FullMethodName = "/mensaje.Mission/NotificarEstrellas"
	Mission_NotificarGolpe_FullMethodName     = "/mensaje.Mission/NotificarGolpe"
)

// MissionClient is the client API for Mission service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// El servicio "Greeter" define un conjunto de funciones remotas.
type MissionClient interface {
	// Nuestra función remota. Recibe un HelloRequest y devuelve un HelloResponse.
	Oferta(ctx context.Context, in *MissionRequest, opts ...grpc.CallOption) (*MissionResponse, error)
	ConfirmMission(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*ConfirmResponse, error)
	Distraccion(ctx context.Context, in *DistraccionRequest, opts ...grpc.CallOption) (*DistraccionResponse, error)
	Golpe(ctx context.Context, in *GolpeRequest, opts ...grpc.CallOption) (*GolpeResponse, error)
	NotificarEstrellas(ctx context.Context, in *AvisoRequest, opts ...grpc.CallOption) (*AvisoResponse, error)
	NotificarGolpe(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*ConfirmResponse, error)
}

type missionClient struct {
	cc grpc.ClientConnInterface
}

func NewMissionClient(cc grpc.ClientConnInterface) MissionClient {
	return &missionClient{cc}
}

func (c *missionClient) Oferta(ctx context.Context, in *MissionRequest, opts ...grpc.CallOption) (*MissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MissionResponse)
	err := c.cc.Invoke(ctx, Mission_Oferta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *missionClient) ConfirmMission(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*ConfirmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmResponse)
	err := c.cc.Invoke(ctx, Mission_ConfirmMission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *missionClient) Distraccion(ctx context.Context, in *DistraccionRequest, opts ...grpc.CallOption) (*DistraccionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DistraccionResponse)
	err := c.cc.Invoke(ctx, Mission_Distraccion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *missionClient) Golpe(ctx context.Context, in *GolpeRequest, opts ...grpc.CallOption) (*GolpeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GolpeResponse)
	err := c.cc.Invoke(ctx, Mission_Golpe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *missionClient) NotificarEstrellas(ctx context.Context, in *AvisoRequest, opts ...grpc.CallOption) (*AvisoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvisoResponse)
	err := c.cc.Invoke(ctx, Mission_NotificarEstrellas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *missionClient) NotificarGolpe(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*ConfirmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmResponse)
	err := c.cc.Invoke(ctx, Mission_NotificarGolpe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MissionServer is the server API for Mission service.
// All implementations must embed UnimplementedMissionServer
// for forward compatibility.
//
// El servicio "Greeter" define un conjunto de funciones remotas.
type MissionServer interface {
	// Nuestra función remota. Recibe un HelloRequest y devuelve un HelloResponse.
	Oferta(context.Context, *MissionRequest) (*MissionResponse, error)
	ConfirmMission(context.Context, *ConfirmRequest) (*ConfirmResponse, error)
	Distraccion(context.Context, *DistraccionRequest) (*DistraccionResponse, error)
	Golpe(context.Context, *GolpeRequest) (*GolpeResponse, error)
	NotificarEstrellas(context.Context, *AvisoRequest) (*AvisoResponse, error)
	NotificarGolpe(context.Context, *ConfirmRequest) (*ConfirmResponse, error)
	mustEmbedUnimplementedMissionServer()
}

// UnimplementedMissionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMissionServer struct{}

func (UnimplementedMissionServer) Oferta(context.Context, *MissionRequest) (*MissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Oferta not implemented")
}
func (UnimplementedMissionServer) ConfirmMission(context.Context, *ConfirmRequest) (*ConfirmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmMission not implemented")
}
func (UnimplementedMissionServer) Distraccion(context.Context, *DistraccionRequest) (*DistraccionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Distraccion not implemented")
}
func (UnimplementedMissionServer) Golpe(context.Context, *GolpeRequest) (*GolpeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Golpe not implemented")
}
func (UnimplementedMissionServer) NotificarEstrellas(context.Context, *AvisoRequest) (*AvisoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotificarEstrellas not implemented")
}
func (UnimplementedMissionServer) NotificarGolpe(context.Context, *ConfirmRequest) (*ConfirmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotificarGolpe not implemented")
}
func (UnimplementedMissionServer) mustEmbedUnimplementedMissionServer() {}
func (UnimplementedMissionServer) testEmbeddedByValue()                 {}

// UnsafeMissionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MissionServer will
// result in compilation errors.
type UnsafeMissionServer interface {
	mustEmbedUnimplementedMissionServer()
}

func RegisterMissionServer(s grpc.ServiceRegistrar, srv MissionServer) {
	// If the following call pancis, it indicates UnimplementedMissionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Mission_ServiceDesc, srv)
}

func _Mission_Oferta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MissionServer).Oferta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mission_Oferta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MissionServer).Oferta(ctx, req.(*MissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mission_ConfirmMission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MissionServer).ConfirmMission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mission_ConfirmMission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MissionServer).ConfirmMission(ctx, req.(*ConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mission_Distraccion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistraccionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MissionServer).Distraccion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mission_Distraccion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MissionServer).Distraccion(ctx, req.(*DistraccionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mission_Golpe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GolpeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MissionServer).Golpe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mission_Golpe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MissionServer).Golpe(ctx, req.(*GolpeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mission_NotificarEstrellas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvisoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MissionServer).NotificarEstrellas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mission_NotificarEstrellas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MissionServer).NotificarEstrellas(ctx, req.(*AvisoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mission_NotificarGolpe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MissionServer).NotificarGolpe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mission_NotificarGolpe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MissionServer).NotificarGolpe(ctx, req.(*ConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Mission_ServiceDesc is the grpc.ServiceDesc for Mission service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mission_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mensaje.Mission",
	HandlerType: (*MissionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Oferta",
			Handler:    _Mission_Oferta_Handler,
		},
		{
			MethodName: "ConfirmMission",
			Handler:    _Mission_ConfirmMission_Handler,
		},
		{
			MethodName: "Distraccion",
			Handler:    _Mission_Distraccion_Handler,
		},
		{
			MethodName: "Golpe",
			Handler:    _Mission_Golpe_Handler,
		},
		{
			MethodName: "NotificarEstrellas",
			Handler:    _Mission_NotificarEstrellas_Handler,
		},
		{
			MethodName: "NotificarGolpe",
			Handler:    _Mission_NotificarGolpe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "michael.proto",
}
