// Especifica la versión de la sintaxis de Protocol Buffers.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: michael.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvisoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pj            string                 `protobuf:"bytes,1,opt,name=pj,proto3" json:"pj,omitempty"`
	Riesgo        int32                  `protobuf:"varint,2,opt,name=riesgo,proto3" json:"riesgo,omitempty"`
	Turnos        int32                  `protobuf:"varint,3,opt,name=turnos,proto3" json:"turnos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvisoRequest) Reset() {
	*x = AvisoRequest{}
	mi := &file_michael_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvisoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvisoRequest) ProtoMessage() {}

func (x *AvisoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_michael_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvisoRequest.ProtoReflect.Descriptor instead.
func (*AvisoRequest) Descriptor() ([]byte, []int) {
	return file_michael_proto_rawDescGZIP(), []int{0}
}

func (x *AvisoRequest) GetPj() string {
	if x != nil {
		return x.Pj
	}
	return ""
}

func (x *AvisoRequest) GetRiesgo() int32 {
	if x != nil {
		return x.Riesgo
	}
	return 0
}

func (x *AvisoRequest) GetTurnos() int32 {
	if x != nil {
		return x.Turnos
	}
	return 0
}

type AvisoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvisoResponse) Reset() {
	*x = AvisoResponse{}
	mi := &file_michael_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvisoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvisoResponse) ProtoMessage() {}

func (x *AvisoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_michael_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvisoResponse.ProtoReflect.Descriptor instead.
func (*AvisoResponse) Descriptor() ([]byte, []int) {
	return file_michael_proto_rawDescGZIP(), []int{1}
}

// El mensaje de solicitud. Contiene el nombre de la persona a saludar.
type MissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rechazo       int32                  `protobuf:"varint,1,opt,name=rechazo,proto3" json:"rechazo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionRequest) Reset() {
	*x = MissionRequest{}
	mi := &file_michael_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionRequest) ProtoMessage() {}

func (x *MissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_michael_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionRequest.ProtoReflect.Descriptor instead.
func (*MissionRequest) Descriptor() ([]byte, []int) {
	return file_michael_proto_rawDescGZIP(), []int{2}
}

func (x *MissionRequest) GetRechazo() int32 {
	if x != nil {
		return x.Rechazo
	}
	return 0
}

// El mensaje de respuesta. Contendrá el saludo final.
type MissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disp          bool                   `protobuf:"varint,1,opt,name=disp,proto3" json:"disp,omitempty"`
	Botin         string                 `protobuf:"bytes,2,opt,name=botin,proto3" json:"botin,omitempty"`
	ProbF         string                 `protobuf:"bytes,3,opt,name=prob_f,json=probF,proto3" json:"prob_f,omitempty"`
	ProbT         string                 `protobuf:"bytes,4,opt,name=prob_t,json=probT,proto3" json:"prob_t,omitempty"`
	Riesgo        string                 `protobuf:"bytes,5,opt,name=riesgo,proto3" json:"riesgo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionResponse) Reset() {
	*x = MissionResponse{}
	mi := &file_michael_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionResponse) ProtoMessage() {}

func (x *MissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_michael_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionResponse.ProtoReflect.Descriptor instead.
func (*MissionResponse) Descriptor() ([]byte, []int) {
	return file_michael_proto_rawDescGZIP(), []int{3}
}

func (x *MissionResponse) GetDisp() bool {
	if x != nil {
		return x.Disp
	}
	return false
}

func (x *MissionResponse) GetBotin() string {
	if x != nil {
		return x.Botin
	}
	return ""
}

func (x *MissionResponse) GetProbF() string {
	if x != nil {
		return x.ProbF
	}
	return ""
}

func (x *MissionResponse) GetProbT() string {
	if x != nil {
		return x.ProbT
	}
	return ""
}

func (x *MissionResponse) GetRiesgo() string {
	if x != nil {
		return x.Riesgo
	}
	return ""
}

type ConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conf          bool                   `protobuf:"varint,1,opt,name=conf,proto3" json:"conf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRequest) Reset() {
	*x = ConfirmRequest{}
	mi := &file_michael_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRequest) ProtoMessage() {}

func (x *ConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_michael_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return file_michael_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmRequest) GetConf() bool {
	if x != nil {
		return x.Conf
	}
	return false
}

type ConfirmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmResponse) Reset() {
	*x = ConfirmResponse{}
	mi := &file_michael_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmResponse) ProtoMessage() {}

func (x *ConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_michael_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmResponse.ProtoReflect.Descriptor instead.
func (*ConfirmResponse) Descriptor() ([]byte, []int) {
	return file_michael_proto_rawDescGZIP(), []int{5}
}

type DistraccionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Turnos        int32                  `protobuf:"varint,1,opt,name=turnos,proto3" json:"turnos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistraccionRequest) Reset() {
	*x = DistraccionRequest{}
	mi := &file_michael_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistraccionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistraccionRequest) ProtoMessage() {}

func (x *DistraccionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_michael_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistraccionRequest.ProtoReflect.Descriptor instead.
func (*DistraccionRequest) Descriptor() ([]byte, []int) {
	return file_michael_proto_rawDescGZIP(), []int{6}
}

func (x *DistraccionRequest) GetTurnos() int32 {
	if x != nil {
		return x.Turnos
	}
	return 0
}

type DistraccionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmacion  bool                   `protobuf:"varint,1,opt,name=confirmacion,proto3" json:"confirmacion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistraccionResponse) Reset() {
	*x = DistraccionResponse{}
	mi := &file_michael_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistraccionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistraccionResponse) ProtoMessage() {}

func (x *DistraccionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_michael_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistraccionResponse.ProtoReflect.Descriptor instead.
func (*DistraccionResponse) Descriptor() ([]byte, []int) {
	return file_michael_proto_rawDescGZIP(), []int{7}
}

func (x *DistraccionResponse) GetConfirmacion() bool {
	if x != nil {
		return x.Confirmacion
	}
	return false
}

type GolpeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Turnos        int32                  `protobuf:"varint,1,opt,name=turnos,proto3" json:"turnos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GolpeRequest) Reset() {
	*x = GolpeRequest{}
	mi := &file_michael_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GolpeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GolpeRequest) ProtoMessage() {}

func (x *GolpeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_michael_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GolpeRequest.ProtoReflect.Descriptor instead.
func (*GolpeRequest) Descriptor() ([]byte, []int) {
	return file_michael_proto_rawDescGZIP(), []int{8}
}

func (x *GolpeRequest) GetTurnos() int32 {
	if x != nil {
		return x.Turnos
	}
	return 0
}

type GolpeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmacion  bool                   `protobuf:"varint,1,opt,name=confirmacion,proto3" json:"confirmacion,omitempty"`
	BotinExtra    int32                  `protobuf:"varint,2,opt,name=botinExtra,proto3" json:"botinExtra,omitempty"`
	Razon         string                 `protobuf:"bytes,3,opt,name=razon,proto3" json:"razon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GolpeResponse) Reset() {
	*x = GolpeResponse{}
	mi := &file_michael_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GolpeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GolpeResponse) ProtoMessage() {}

func (x *GolpeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_michael_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GolpeResponse.ProtoReflect.Descriptor instead.
func (*GolpeResponse) Descriptor() ([]byte, []int) {
	return file_michael_proto_rawDescGZIP(), []int{9}
}

func (x *GolpeResponse) GetConfirmacion() bool {
	if x != nil {
		return x.Confirmacion
	}
	return false
}

func (x *GolpeResponse) GetBotinExtra() int32 {
	if x != nil {
		return x.BotinExtra
	}
	return 0
}

func (x *GolpeResponse) GetRazon() string {
	if x != nil {
		return x.Razon
	}
	return ""
}

var File_michael_proto protoreflect.FileDescriptor

const file_michael_proto_rawDesc = "" +
	"\n" +
	"\rmichael.proto\x12\amensaje\"N\n" +
	"\fAvisoRequest\x12\x0e\n" +
	"\x02pj\x18\x01 \x01(\tR\x02pj\x12\x16\n" +
	"\x06riesgo\x18\x02 \x01(\x05R\x06riesgo\x12\x16\n" +
	"\x06turnos\x18\x03 \x01(\x05R\x06turnos\"\x0f\n" +
	"\rAvisoResponse\"*\n" +
	"\x0eMissionRequest\x12\x18\n" +
	"\arechazo\x18\x01 \x01(\x05R\arechazo\"\x81\x01\n" +
	"\x0fMissionResponse\x12\x12\n" +
	"\x04disp\x18\x01 \x01(\bR\x04disp\x12\x14\n" +
	"\x05botin\x18\x02 \x01(\tR\x05botin\x12\x15\n" +
	"\x06prob_f\x18\x03 \x01(\tR\x05probF\x12\x15\n" +
	"\x06prob_t\x18\x04 \x01(\tR\x05probT\x12\x16\n" +
	"\x06riesgo\x18\x05 \x01(\tR\x06riesgo\"$\n" +
	"\x0eConfirmRequest\x12\x12\n" +
	"\x04conf\x18\x01 \x01(\bR\x04conf\"\x11\n" +
	"\x0fConfirmResponse\",\n" +
	"\x12DistraccionRequest\x12\x16\n" +
	"\x06turnos\x18\x01 \x01(\x05R\x06turnos\"9\n" +
	"\x13DistraccionResponse\x12\"\n" +
	"\fconfirmacion\x18\x01 \x01(\bR\fconfirmacion\"&\n" +
	"\fGolpeRequest\x12\x16\n" +
	"\x06turnos\x18\x01 \x01(\x05R\x06turnos\"i\n" +
	"\rGolpeResponse\x12\"\n" +
	"\fconfirmacion\x18\x01 \x01(\bR\fconfirmacion\x12\x1e\n" +
	"\n" +
	"botinExtra\x18\x02 \x01(\x05R\n" +
	"botinExtra\x12\x14\n" +
	"\x05razon\x18\x03 \x01(\tR\x05razon2\x97\x03\n" +
	"\aMission\x12;\n" +
	"\x06Oferta\x12\x17.mensaje.MissionRequest\x1a\x18.mensaje.MissionResponse\x12C\n" +
	"\x0eConfirmMission\x12\x17.mensaje.ConfirmRequest\x1a\x18.mensaje.ConfirmResponse\x12H\n" +
	"\vDistraccion\x12\x1b.mensaje.DistraccionRequest\x1a\x1c.mensaje.DistraccionResponse\x126\n" +
	"\x05Golpe\x12\x15.mensaje.GolpeRequest\x1a\x16.mensaje.GolpeResponse\x12C\n" +
	"\x12NotificarEstrellas\x12\x15.mensaje.AvisoRequest\x1a\x16.mensaje.AvisoResponse\x12C\n" +
	"\x0eNotificarGolpe\x12\x17.mensaje.ConfirmRequest\x1a\x18.mensaje.ConfirmResponseB\x13Z\x11michael-sys/protob\x06proto3"

var (
	file_michael_proto_rawDescOnce sync.Once
	file_michael_proto_rawDescData []byte
)

func file_michael_proto_rawDescGZIP() []byte {
	file_michael_proto_rawDescOnce.Do(func() {
		file_michael_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_michael_proto_rawDesc), len(file_michael_proto_rawDesc)))
	})
	return file_michael_proto_rawDescData
}

var file_michael_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_michael_proto_goTypes = []any{
	(*AvisoRequest)(nil),        // 0: mensaje.AvisoRequest
	(*AvisoResponse)(nil),       // 1: mensaje.AvisoResponse
	(*MissionRequest)(nil),      // 2: mensaje.MissionRequest
	(*MissionResponse)(nil),     // 3: mensaje.MissionResponse
	(*ConfirmRequest)(nil),      // 4: mensaje.ConfirmRequest
	(*ConfirmResponse)(nil),     // 5: mensaje.ConfirmResponse
	(*DistraccionRequest)(nil),  // 6: mensaje.DistraccionRequest
	(*DistraccionResponse)(nil), // 7: mensaje.DistraccionResponse
	(*GolpeRequest)(nil),        // 8: mensaje.GolpeRequest
	(*GolpeResponse)(nil),       // 9: mensaje.GolpeResponse
}
var file_michael_proto_depIdxs = []int32{
	2, // 0: mensaje.Mission.Oferta:input_type -> mensaje.MissionRequest
	4, // 1: mensaje.Mission.ConfirmMission:input_type -> mensaje.ConfirmRequest
	6, // 2: mensaje.Mission.Distraccion:input_type -> mensaje.DistraccionRequest
	8, // 3: mensaje.Mission.Golpe:input_type -> mensaje.GolpeRequest
	0, // 4: mensaje.Mission.NotificarEstrellas:input_type -> mensaje.AvisoRequest
	4, // 5: mensaje.Mission.NotificarGolpe:input_type -> mensaje.ConfirmRequest
	3, // 6: mensaje.Mission.Oferta:output_type -> mensaje.MissionResponse
	5, // 7: mensaje.Mission.ConfirmMission:output_type -> mensaje.ConfirmResponse
	7, // 8: mensaje.Mission.Distraccion:output_type -> mensaje.DistraccionResponse
	9, // 9: mensaje.Mission.Golpe:output_type -> mensaje.GolpeResponse
	1, // 10: mensaje.Mission.NotificarEstrellas:output_type -> mensaje.AvisoResponse
	5, // 11: mensaje.Mission.NotificarGolpe:output_type -> mensaje.ConfirmResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_michael_proto_init() }
func file_michael_proto_init() {
	if File_michael_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_michael_proto_rawDesc), len(file_michael_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_michael_proto_goTypes,
		DependencyIndexes: file_michael_proto_depIdxs,
		MessageInfos:      file_michael_proto_msgTypes,
	}.Build()
	File_michael_proto = out.File
	file_michael_proto_goTypes = nil
	file_michael_proto_depIdxs = nil
}
