// Especifica la versión de la sintaxis de Protocol Buffers.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: michael.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// El mensaje de solicitud. Contiene el nombre de la persona a saludar.
type MissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rechazo       int32                  `protobuf:"varint,1,opt,name=rechazo,proto3" json:"rechazo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionRequest) Reset() {
	*x = MissionRequest{}
	mi := &file_michael_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionRequest) ProtoMessage() {}

func (x *MissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_michael_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionRequest.ProtoReflect.Descriptor instead.
func (*MissionRequest) Descriptor() ([]byte, []int) {
	return file_michael_proto_rawDescGZIP(), []int{0}
}

func (x *MissionRequest) GetRechazo() int32 {
	if x != nil {
		return x.Rechazo
	}
	return 0
}

// El mensaje de respuesta. Contendrá el saludo final.
type MissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disp          bool                   `protobuf:"varint,1,opt,name=disp,proto3" json:"disp,omitempty"`
	Botin         int32                  `protobuf:"varint,2,opt,name=botin,proto3" json:"botin,omitempty"`
	ProbF         int32                  `protobuf:"varint,3,opt,name=prob_f,json=probF,proto3" json:"prob_f,omitempty"`
	ProbT         int32                  `protobuf:"varint,4,opt,name=prob_t,json=probT,proto3" json:"prob_t,omitempty"`
	Riesgo        int32                  `protobuf:"varint,5,opt,name=riesgo,proto3" json:"riesgo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionResponse) Reset() {
	*x = MissionResponse{}
	mi := &file_michael_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionResponse) ProtoMessage() {}

func (x *MissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_michael_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionResponse.ProtoReflect.Descriptor instead.
func (*MissionResponse) Descriptor() ([]byte, []int) {
	return file_michael_proto_rawDescGZIP(), []int{1}
}

func (x *MissionResponse) GetDisp() bool {
	if x != nil {
		return x.Disp
	}
	return false
}

func (x *MissionResponse) GetBotin() int32 {
	if x != nil {
		return x.Botin
	}
	return 0
}

func (x *MissionResponse) GetProbF() int32 {
	if x != nil {
		return x.ProbF
	}
	return 0
}

func (x *MissionResponse) GetProbT() int32 {
	if x != nil {
		return x.ProbT
	}
	return 0
}

func (x *MissionResponse) GetRiesgo() int32 {
	if x != nil {
		return x.Riesgo
	}
	return 0
}

type ConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conf          bool                   `protobuf:"varint,1,opt,name=conf,proto3" json:"conf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRequest) Reset() {
	*x = ConfirmRequest{}
	mi := &file_michael_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRequest) ProtoMessage() {}

func (x *ConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_michael_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return file_michael_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmRequest) GetConf() bool {
	if x != nil {
		return x.Conf
	}
	return false
}

type ConfirmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmResponse) Reset() {
	*x = ConfirmResponse{}
	mi := &file_michael_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmResponse) ProtoMessage() {}

func (x *ConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_michael_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmResponse.ProtoReflect.Descriptor instead.
func (*ConfirmResponse) Descriptor() ([]byte, []int) {
	return file_michael_proto_rawDescGZIP(), []int{3}
}

var File_michael_proto protoreflect.FileDescriptor

const file_michael_proto_rawDesc = "" +
	"\n" +
	"\rmichael.proto\x12\amensaje\"*\n" +
	"\x0eMissionRequest\x12\x18\n" +
	"\arechazo\x18\x01 \x01(\x05R\arechazo\"\x81\x01\n" +
	"\x0fMissionResponse\x12\x12\n" +
	"\x04disp\x18\x01 \x01(\bR\x04disp\x12\x14\n" +
	"\x05botin\x18\x02 \x01(\x05R\x05botin\x12\x15\n" +
	"\x06prob_f\x18\x03 \x01(\x05R\x05probF\x12\x15\n" +
	"\x06prob_t\x18\x04 \x01(\x05R\x05probT\x12\x16\n" +
	"\x06riesgo\x18\x05 \x01(\x05R\x06riesgo\"$\n" +
	"\x0eConfirmRequest\x12\x12\n" +
	"\x04conf\x18\x01 \x01(\bR\x04conf\"\x11\n" +
	"\x0fConfirmResponse2\x8b\x01\n" +
	"\aMission\x12;\n" +
	"\x06Oferta\x12\x17.mensaje.MissionRequest\x1a\x18.mensaje.MissionResponse\x12C\n" +
	"\x0eConfirmMission\x12\x17.mensaje.ConfirmRequest\x1a\x18.mensaje.ConfirmResponseB\x13Z\x11michael-sys/protob\x06proto3"

var (
	file_michael_proto_rawDescOnce sync.Once
	file_michael_proto_rawDescData []byte
)

func file_michael_proto_rawDescGZIP() []byte {
	file_michael_proto_rawDescOnce.Do(func() {
		file_michael_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_michael_proto_rawDesc), len(file_michael_proto_rawDesc)))
	})
	return file_michael_proto_rawDescData
}

var file_michael_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_michael_proto_goTypes = []any{
	(*MissionRequest)(nil),  // 0: mensaje.MissionRequest
	(*MissionResponse)(nil), // 1: mensaje.MissionResponse
	(*ConfirmRequest)(nil),  // 2: mensaje.ConfirmRequest
	(*ConfirmResponse)(nil), // 3: mensaje.ConfirmResponse
}
var file_michael_proto_depIdxs = []int32{
	0, // 0: mensaje.Mission.Oferta:input_type -> mensaje.MissionRequest
	2, // 1: mensaje.Mission.ConfirmMission:input_type -> mensaje.ConfirmRequest
	1, // 2: mensaje.Mission.Oferta:output_type -> mensaje.MissionResponse
	3, // 3: mensaje.Mission.ConfirmMission:output_type -> mensaje.ConfirmResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_michael_proto_init() }
func file_michael_proto_init() {
	if File_michael_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_michael_proto_rawDesc), len(file_michael_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_michael_proto_goTypes,
		DependencyIndexes: file_michael_proto_depIdxs,
		MessageInfos:      file_michael_proto_msgTypes,
	}.Build()
	File_michael_proto = out.File
	file_michael_proto_goTypes = nil
	file_michael_proto_depIdxs = nil
}
