// Especifica la versión de la sintaxis de Protocol Buffers.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: trevor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DistraccionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Turnos        int32                  `protobuf:"varint,1,opt,name=turnos,proto3" json:"turnos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistraccionRequest) Reset() {
	*x = DistraccionRequest{}
	mi := &file_trevor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistraccionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistraccionRequest) ProtoMessage() {}

func (x *DistraccionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trevor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistraccionRequest.ProtoReflect.Descriptor instead.
func (*DistraccionRequest) Descriptor() ([]byte, []int) {
	return file_trevor_proto_rawDescGZIP(), []int{0}
}

func (x *DistraccionRequest) GetTurnos() int32 {
	if x != nil {
		return x.Turnos
	}
	return 0
}

type DistraccionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmacion  bool                   `protobuf:"varint,1,opt,name=confirmacion,proto3" json:"confirmacion,omitempty"`
	Razon         string                 `protobuf:"bytes,2,opt,name=razon,proto3" json:"razon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistraccionResponse) Reset() {
	*x = DistraccionResponse{}
	mi := &file_trevor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistraccionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistraccionResponse) ProtoMessage() {}

func (x *DistraccionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trevor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistraccionResponse.ProtoReflect.Descriptor instead.
func (*DistraccionResponse) Descriptor() ([]byte, []int) {
	return file_trevor_proto_rawDescGZIP(), []int{1}
}

func (x *DistraccionResponse) GetConfirmacion() bool {
	if x != nil {
		return x.Confirmacion
	}
	return false
}

func (x *DistraccionResponse) GetRazon() string {
	if x != nil {
		return x.Razon
	}
	return ""
}

type GolpeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Turnos        int32                  `protobuf:"varint,1,opt,name=turnos,proto3" json:"turnos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GolpeRequest) Reset() {
	*x = GolpeRequest{}
	mi := &file_trevor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GolpeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GolpeRequest) ProtoMessage() {}

func (x *GolpeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trevor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GolpeRequest.ProtoReflect.Descriptor instead.
func (*GolpeRequest) Descriptor() ([]byte, []int) {
	return file_trevor_proto_rawDescGZIP(), []int{2}
}

func (x *GolpeRequest) GetTurnos() int32 {
	if x != nil {
		return x.Turnos
	}
	return 0
}

type GolpeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmacion  bool                   `protobuf:"varint,1,opt,name=confirmacion,proto3" json:"confirmacion,omitempty"`
	BotinExtra    int32                  `protobuf:"varint,2,opt,name=botinExtra,proto3" json:"botinExtra,omitempty"`
	Razon         string                 `protobuf:"bytes,3,opt,name=razon,proto3" json:"razon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GolpeResponse) Reset() {
	*x = GolpeResponse{}
	mi := &file_trevor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GolpeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GolpeResponse) ProtoMessage() {}

func (x *GolpeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trevor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GolpeResponse.ProtoReflect.Descriptor instead.
func (*GolpeResponse) Descriptor() ([]byte, []int) {
	return file_trevor_proto_rawDescGZIP(), []int{3}
}

func (x *GolpeResponse) GetConfirmacion() bool {
	if x != nil {
		return x.Confirmacion
	}
	return false
}

func (x *GolpeResponse) GetBotinExtra() int32 {
	if x != nil {
		return x.BotinExtra
	}
	return 0
}

func (x *GolpeResponse) GetRazon() string {
	if x != nil {
		return x.Razon
	}
	return ""
}

var File_trevor_proto protoreflect.FileDescriptor

const file_trevor_proto_rawDesc = "" +
	"\n" +
	"\ftrevor.proto\x12\amensaje\",\n" +
	"\x12DistraccionRequest\x12\x16\n" +
	"\x06turnos\x18\x01 \x01(\x05R\x06turnos\"O\n" +
	"\x13DistraccionResponse\x12\"\n" +
	"\fconfirmacion\x18\x01 \x01(\bR\fconfirmacion\x12\x14\n" +
	"\x05razon\x18\x02 \x01(\tR\x05razon\"&\n" +
	"\fGolpeRequest\x12\x16\n" +
	"\x06turnos\x18\x01 \x01(\x05R\x06turnos\"i\n" +
	"\rGolpeResponse\x12\"\n" +
	"\fconfirmacion\x18\x01 \x01(\bR\fconfirmacion\x12\x1e\n" +
	"\n" +
	"botinExtra\x18\x02 \x01(\x05R\n" +
	"botinExtra\x12\x14\n" +
	"\x05razon\x18\x03 \x01(\tR\x05razon2\x8b\x01\n" +
	"\aMission\x12H\n" +
	"\vDistraccion\x12\x1b.mensaje.DistraccionRequest\x1a\x1c.mensaje.DistraccionResponse\x126\n" +
	"\x05Golpe\x12\x15.mensaje.GolpeRequest\x1a\x16.mensaje.GolpeResponseB\x12Z\x10trevor-sys/protob\x06proto3"

var (
	file_trevor_proto_rawDescOnce sync.Once
	file_trevor_proto_rawDescData []byte
)

func file_trevor_proto_rawDescGZIP() []byte {
	file_trevor_proto_rawDescOnce.Do(func() {
		file_trevor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trevor_proto_rawDesc), len(file_trevor_proto_rawDesc)))
	})
	return file_trevor_proto_rawDescData
}

var file_trevor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_trevor_proto_goTypes = []any{
	(*DistraccionRequest)(nil),  // 0: mensaje.DistraccionRequest
	(*DistraccionResponse)(nil), // 1: mensaje.DistraccionResponse
	(*GolpeRequest)(nil),        // 2: mensaje.GolpeRequest
	(*GolpeResponse)(nil),       // 3: mensaje.GolpeResponse
}
var file_trevor_proto_depIdxs = []int32{
	0, // 0: mensaje.Mission.Distraccion:input_type -> mensaje.DistraccionRequest
	2, // 1: mensaje.Mission.Golpe:input_type -> mensaje.GolpeRequest
	1, // 2: mensaje.Mission.Distraccion:output_type -> mensaje.DistraccionResponse
	3, // 3: mensaje.Mission.Golpe:output_type -> mensaje.GolpeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trevor_proto_init() }
func file_trevor_proto_init() {
	if File_trevor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trevor_proto_rawDesc), len(file_trevor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trevor_proto_goTypes,
		DependencyIndexes: file_trevor_proto_depIdxs,
		MessageInfos:      file_trevor_proto_msgTypes,
	}.Build()
	File_trevor_proto = out.File
	file_trevor_proto_goTypes = nil
	file_trevor_proto_depIdxs = nil
}
