// Especifica la versión de la sintaxis de Protocol Buffers.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: lester.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// El mensaje de solicitud. Contiene el nombre de la persona a saludar.
type MissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pregunta      string                 `protobuf:"bytes,1,opt,name=pregunta,proto3" json:"pregunta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionRequest) Reset() {
	*x = MissionRequest{}
	mi := &file_lester_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionRequest) ProtoMessage() {}

func (x *MissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lester_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionRequest.ProtoReflect.Descriptor instead.
func (*MissionRequest) Descriptor() ([]byte, []int) {
	return file_lester_proto_rawDescGZIP(), []int{0}
}

func (x *MissionRequest) GetPregunta() string {
	if x != nil {
		return x.Pregunta
	}
	return ""
}

// El mensaje de respuesta. Contendrá el saludo final.
type MissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hay           string                 `protobuf:"bytes,1,opt,name=hay,proto3" json:"hay,omitempty"`
	Botin         string                 `protobuf:"bytes,2,opt,name=botin,proto3" json:"botin,omitempty"`
	ProbF         string                 `protobuf:"bytes,3,opt,name=prob_f,json=probF,proto3" json:"prob_f,omitempty"`
	ProbT         string                 `protobuf:"bytes,4,opt,name=prob_t,json=probT,proto3" json:"prob_t,omitempty"`
	Riesgo        string                 `protobuf:"bytes,5,opt,name=riesgo,proto3" json:"riesgo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionResponse) Reset() {
	*x = MissionResponse{}
	mi := &file_lester_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionResponse) ProtoMessage() {}

func (x *MissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lester_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionResponse.ProtoReflect.Descriptor instead.
func (*MissionResponse) Descriptor() ([]byte, []int) {
	return file_lester_proto_rawDescGZIP(), []int{1}
}

func (x *MissionResponse) GetHay() string {
	if x != nil {
		return x.Hay
	}
	return ""
}

func (x *MissionResponse) GetBotin() string {
	if x != nil {
		return x.Botin
	}
	return ""
}

func (x *MissionResponse) GetProbF() string {
	if x != nil {
		return x.ProbF
	}
	return ""
}

func (x *MissionResponse) GetProbT() string {
	if x != nil {
		return x.ProbT
	}
	return ""
}

func (x *MissionResponse) GetRiesgo() string {
	if x != nil {
		return x.Riesgo
	}
	return ""
}

var File_lester_proto protoreflect.FileDescriptor

const file_lester_proto_rawDesc = "" +
	"\n" +
	"\flester.proto\x12\amensaje\",\n" +
	"\x0eMissionRequest\x12\x1a\n" +
	"\bpregunta\x18\x01 \x01(\tR\bpregunta\"\x7f\n" +
	"\x0fMissionResponse\x12\x10\n" +
	"\x03hay\x18\x01 \x01(\tR\x03hay\x12\x14\n" +
	"\x05botin\x18\x02 \x01(\tR\x05botin\x12\x15\n" +
	"\x06prob_f\x18\x03 \x01(\tR\x05probF\x12\x15\n" +
	"\x06prob_t\x18\x04 \x01(\tR\x05probT\x12\x16\n" +
	"\x06riesgo\x18\x05 \x01(\tR\x06riesgo2K\n" +
	"\aGreeter\x12@\n" +
	"\vGiveMission\x12\x17.mensaje.MissionRequest\x1a\x18.mensaje.MissionResponseB\x12Z\x10lester-sys/protob\x06proto3"

var (
	file_lester_proto_rawDescOnce sync.Once
	file_lester_proto_rawDescData []byte
)

func file_lester_proto_rawDescGZIP() []byte {
	file_lester_proto_rawDescOnce.Do(func() {
		file_lester_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lester_proto_rawDesc), len(file_lester_proto_rawDesc)))
	})
	return file_lester_proto_rawDescData
}

var file_lester_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lester_proto_goTypes = []any{
	(*MissionRequest)(nil),  // 0: mensaje.MissionRequest
	(*MissionResponse)(nil), // 1: mensaje.MissionResponse
}
var file_lester_proto_depIdxs = []int32{
	0, // 0: mensaje.Greeter.GiveMission:input_type -> mensaje.MissionRequest
	1, // 1: mensaje.Greeter.GiveMission:output_type -> mensaje.MissionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lester_proto_init() }
func file_lester_proto_init() {
	if File_lester_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lester_proto_rawDesc), len(file_lester_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lester_proto_goTypes,
		DependencyIndexes: file_lester_proto_depIdxs,
		MessageInfos:      file_lester_proto_msgTypes,
	}.Build()
	File_lester_proto = out.File
	file_lester_proto_goTypes = nil
	file_lester_proto_depIdxs = nil
}
