// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: franklin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DistraccionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Turnos        int32                  `protobuf:"varint,1,opt,name=turnos,proto3" json:"turnos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistraccionRequest) Reset() {
	*x = DistraccionRequest{}
	mi := &file_franklin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistraccionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistraccionRequest) ProtoMessage() {}

func (x *DistraccionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_franklin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistraccionRequest.ProtoReflect.Descriptor instead.
func (*DistraccionRequest) Descriptor() ([]byte, []int) {
	return file_franklin_proto_rawDescGZIP(), []int{0}
}

func (x *DistraccionRequest) GetTurnos() int32 {
	if x != nil {
		return x.Turnos
	}
	return 0
}

type DistraccionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmacion  bool                   `protobuf:"varint,1,opt,name=confirmacion,proto3" json:"confirmacion,omitempty"`
	Razon         string                 `protobuf:"bytes,2,opt,name=razon,proto3" json:"razon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistraccionResponse) Reset() {
	*x = DistraccionResponse{}
	mi := &file_franklin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistraccionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistraccionResponse) ProtoMessage() {}

func (x *DistraccionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_franklin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistraccionResponse.ProtoReflect.Descriptor instead.
func (*DistraccionResponse) Descriptor() ([]byte, []int) {
	return file_franklin_proto_rawDescGZIP(), []int{1}
}

func (x *DistraccionResponse) GetConfirmacion() bool {
	if x != nil {
		return x.Confirmacion
	}
	return false
}

func (x *DistraccionResponse) GetRazon() string {
	if x != nil {
		return x.Razon
	}
	return ""
}

type GolpeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Turnos        int32                  `protobuf:"varint,1,opt,name=turnos,proto3" json:"turnos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GolpeRequest) Reset() {
	*x = GolpeRequest{}
	mi := &file_franklin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GolpeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GolpeRequest) ProtoMessage() {}

func (x *GolpeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_franklin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GolpeRequest.ProtoReflect.Descriptor instead.
func (*GolpeRequest) Descriptor() ([]byte, []int) {
	return file_franklin_proto_rawDescGZIP(), []int{2}
}

func (x *GolpeRequest) GetTurnos() int32 {
	if x != nil {
		return x.Turnos
	}
	return 0
}

type GolpeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmacion  bool                   `protobuf:"varint,1,opt,name=confirmacion,proto3" json:"confirmacion,omitempty"`
	BotinExtra    int32                  `protobuf:"varint,2,opt,name=botinExtra,proto3" json:"botinExtra,omitempty"`
	Razon         string                 `protobuf:"bytes,3,opt,name=razon,proto3" json:"razon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GolpeResponse) Reset() {
	*x = GolpeResponse{}
	mi := &file_franklin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GolpeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GolpeResponse) ProtoMessage() {}

func (x *GolpeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_franklin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GolpeResponse.ProtoReflect.Descriptor instead.
func (*GolpeResponse) Descriptor() ([]byte, []int) {
	return file_franklin_proto_rawDescGZIP(), []int{3}
}

func (x *GolpeResponse) GetConfirmacion() bool {
	if x != nil {
		return x.Confirmacion
	}
	return false
}

func (x *GolpeResponse) GetBotinExtra() int32 {
	if x != nil {
		return x.BotinExtra
	}
	return 0
}

func (x *GolpeResponse) GetRazon() string {
	if x != nil {
		return x.Razon
	}
	return ""
}

type PagoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Victoria      bool                   `protobuf:"varint,1,opt,name=victoria,proto3" json:"victoria,omitempty"`
	Fase          string                 `protobuf:"bytes,2,opt,name=fase,proto3" json:"fase,omitempty"`
	Who           string                 `protobuf:"bytes,3,opt,name=who,proto3" json:"who,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagoRequest) Reset() {
	*x = PagoRequest{}
	mi := &file_franklin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagoRequest) ProtoMessage() {}

func (x *PagoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_franklin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagoRequest.ProtoReflect.Descriptor instead.
func (*PagoRequest) Descriptor() ([]byte, []int) {
	return file_franklin_proto_rawDescGZIP(), []int{4}
}

func (x *PagoRequest) GetVictoria() bool {
	if x != nil {
		return x.Victoria
	}
	return false
}

func (x *PagoRequest) GetFase() string {
	if x != nil {
		return x.Fase
	}
	return ""
}

func (x *PagoRequest) GetWho() string {
	if x != nil {
		return x.Who
	}
	return ""
}

type PagoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msj           string                 `protobuf:"bytes,1,opt,name=msj,proto3" json:"msj,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagoResponse) Reset() {
	*x = PagoResponse{}
	mi := &file_franklin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagoResponse) ProtoMessage() {}

func (x *PagoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_franklin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagoResponse.ProtoReflect.Descriptor instead.
func (*PagoResponse) Descriptor() ([]byte, []int) {
	return file_franklin_proto_rawDescGZIP(), []int{5}
}

func (x *PagoResponse) GetMsj() string {
	if x != nil {
		return x.Msj
	}
	return ""
}

var File_franklin_proto protoreflect.FileDescriptor

const file_franklin_proto_rawDesc = "" +
	"\n" +
	"\x0efranklin.proto\x12\amensaje\",\n" +
	"\x12DistraccionRequest\x12\x16\n" +
	"\x06turnos\x18\x01 \x01(\x05R\x06turnos\"O\n" +
	"\x13DistraccionResponse\x12\"\n" +
	"\fconfirmacion\x18\x01 \x01(\bR\fconfirmacion\x12\x14\n" +
	"\x05razon\x18\x02 \x01(\tR\x05razon\"&\n" +
	"\fGolpeRequest\x12\x16\n" +
	"\x06turnos\x18\x01 \x01(\x05R\x06turnos\"i\n" +
	"\rGolpeResponse\x12\"\n" +
	"\fconfirmacion\x18\x01 \x01(\bR\fconfirmacion\x12\x1e\n" +
	"\n" +
	"botinExtra\x18\x02 \x01(\x05R\n" +
	"botinExtra\x12\x14\n" +
	"\x05razon\x18\x03 \x01(\tR\x05razon\"O\n" +
	"\vPagoRequest\x12\x1a\n" +
	"\bvictoria\x18\x01 \x01(\bR\bvictoria\x12\x12\n" +
	"\x04fase\x18\x02 \x01(\tR\x04fase\x12\x10\n" +
	"\x03who\x18\x03 \x01(\tR\x03who\" \n" +
	"\fPagoResponse\x12\x10\n" +
	"\x03msj\x18\x01 \x01(\tR\x03msj2\xcc\x01\n" +
	"\aMission\x12H\n" +
	"\vDistraccion\x12\x1b.mensaje.DistraccionRequest\x1a\x1c.mensaje.DistraccionResponse\x126\n" +
	"\x05Golpe\x12\x15.mensaje.GolpeRequest\x1a\x16.mensaje.GolpeResponse\x12?\n" +
	"\x10ConfirmacionPago\x12\x14.mensaje.PagoRequest\x1a\x15.mensaje.PagoResponseB\x14Z\x12franklin-sys/protob\x06proto3"

var (
	file_franklin_proto_rawDescOnce sync.Once
	file_franklin_proto_rawDescData []byte
)

func file_franklin_proto_rawDescGZIP() []byte {
	file_franklin_proto_rawDescOnce.Do(func() {
		file_franklin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_franklin_proto_rawDesc), len(file_franklin_proto_rawDesc)))
	})
	return file_franklin_proto_rawDescData
}

var file_franklin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_franklin_proto_goTypes = []any{
	(*DistraccionRequest)(nil),  // 0: mensaje.DistraccionRequest
	(*DistraccionResponse)(nil), // 1: mensaje.DistraccionResponse
	(*GolpeRequest)(nil),        // 2: mensaje.GolpeRequest
	(*GolpeResponse)(nil),       // 3: mensaje.GolpeResponse
	(*PagoRequest)(nil),         // 4: mensaje.PagoRequest
	(*PagoResponse)(nil),        // 5: mensaje.PagoResponse
}
var file_franklin_proto_depIdxs = []int32{
	0, // 0: mensaje.Mission.Distraccion:input_type -> mensaje.DistraccionRequest
	2, // 1: mensaje.Mission.Golpe:input_type -> mensaje.GolpeRequest
	4, // 2: mensaje.Mission.ConfirmacionPago:input_type -> mensaje.PagoRequest
	1, // 3: mensaje.Mission.Distraccion:output_type -> mensaje.DistraccionResponse
	3, // 4: mensaje.Mission.Golpe:output_type -> mensaje.GolpeResponse
	5, // 5: mensaje.Mission.ConfirmacionPago:output_type -> mensaje.PagoResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_franklin_proto_init() }
func file_franklin_proto_init() {
	if File_franklin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_franklin_proto_rawDesc), len(file_franklin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_franklin_proto_goTypes,
		DependencyIndexes: file_franklin_proto_depIdxs,
		MessageInfos:      file_franklin_proto_msgTypes,
	}.Build()
	File_franklin_proto = out.File
	file_franklin_proto_goTypes = nil
	file_franklin_proto_depIdxs = nil
}
